language: python
python:
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
install:
  - pip install -e .
script:
  - py.test --cov .
after_success: coveralls
