system:
  ip_address: 10.0.0.1
  online: true
  default_path: log/
  pretilt: 27
  relative_lm_position:
  - 0.0499092
  - -0.0001143
  fibsem_min_position: -10.e-3
  fibsem_max_position: 10.e-3
  lm_min_position: 40.e-3
  lm_max_position: 60.e-3

  save_config_on_exit: false
serial:
  port: COM3
  baudrate: 115200
  timeout: 1
lm_objective:
  pin: P04
lm:
  default_laser: laser640
  lasers:
  - name: laser405
    wavelength: 405
    pin: P00
    ID: laser4
    colour:
    - 0
    - 0
    - 255
    power: 10.0
    exposure_time: 600.0
    volume_enabled: false
  - name: laser488
    wavelength: 488
    pin: P01
    ID: laser3
    colour:
    - 0
    - 255
    - 0
    power: 10.0
    exposure_time: 1000.0
    volume_enabled: false
  - name: laser561
    wavelength: 561
    pin: P02
    ID: laser2
    colour:
    - 255
    - 143
    - 51
    power: 10.0
    exposure_time: 100.0
    volume_enabled: false
  - name: laser640
    wavelength: 640
    pin: P03
    ID: laser1
    colour:
    - 148
    - 43
    - 35
    power: 21.0
    exposure_time: 1000.0
    volume_enabled: true
imaging:
  lm:
    trigger_mode: Hardware
    autosave: false
    color: false
    filter_strength: 0
    camera:
      max_num_buffer: 5
      image_frame_interval: null
      pixel_size: 5.86e-06
      objective_mag: 20
      telescope_mag: 3.333
  ib:
    relative_angle: 52
    autosave: false
    filter_strength: 3
  volume:
    time_delay: 0.1
    autosave: true
    count_max: 2
    threshold: 10
    slice_interrupt_pin: P04
  SIM:
    angles: 3
    phases: 3
  crosshairs:
    thickness: 0.1
    length: 10
    color: xkcd:yellow
  correlation:
    autosave: false
lamella:
  lamella_width: 1.2e-05
  lamella_height: 1.0e-05
  milling_depth: 5.0e-06
  milling_current: 10.1e-12
  # milling_current: 2.4e-09
  hfw: 0.00015
  upper_height: 5.0e-06
  lower_height: 2.5e-06
