system:
  ip_address: 10.0.0.1
  online: True
  default_path: log/
serial:
  port: "COM3"
  # port: "COM15"
  baudrate: 115200
  timeout: 1
lm_objective:
  pin: P04
lm:
  default_laser: laser488
  lasers:
    - name: laser405
      wavelength: 405 # nm
      pin: P00
      ID: laser4
      colour: [0, 0, 255]
    - name: laser488
      wavelength: 488 # nm
      pin: P01
      ID: laser3
      colour: [0, 255, 0]
    - name: laser561
      wavelength: 561 # nm
      pin: P02
      ID: laser2
      colour: [255, 143, 51]
    - name: laser640
      wavelength: 640 # nm
      pin: P03
      ID: laser1
      colour: [148, 43, 35]
imaging:
  lm:
    trigger_mode: hardware # (str) 'software' [default] or 'hardware'
    autosave: False
    color: False
    filter_strength: 0 # int or None
    camera:
      pin: P14
      max_num_buffer: 5 # max number of images to store in the buffer
      image_frame_interval: NULL # (float) time between frames if desired
      pixel_size: 5.86e-6 # acA1920-155um
  ib:
    pretilt: 52 # TODO: check if this can be always assumed
    autosave: False
    filter_strength: 3 # int or None
  volume:
    time_delay: 0.1 #sec
    autosave: True
    count_max: 2
    threshold: 10
  SIM:
    angles: 3
    phases: 3
  crosshairs:
    thickness: 0.1 # in % of image width
    length: 10 # in % of image width
    color: xkcd:yellow
