system:
  ip_address: 10.0.0.1
  online: true
  default_path: log/
  pretilt: 27
serial:
  port: COM3
  baudrate: 115200
  timeout: 1
lm_objective:
  pin: P04
lm:
  default_laser: laser488
  lasers:
  - name: laser405
    wavelength: 405
    pin: P00
    ID: laser4
    colour:
    - 0
    - 0
    - 255
    power: 10.0
    exposure_time: 1000.0
    volume_enabled: false
  - name: laser488
    wavelength: 488
    pin: P01
    ID: laser3
    colour:
    - 0
    - 255
    - 0
    power: 10.0
    exposure_time: 1000.0
    volume_enabled: false
  - name: laser561
    wavelength: 561
    pin: P02
    ID: laser2
    colour:
    - 255
    - 143
    - 51
    power: 10.0
    exposure_time: 200.0
    volume_enabled: true
  - name: laser640
    wavelength: 640
    pin: P03
    ID: laser1
    colour:
    - 148
    - 43
    - 35
    power: 9.0
    exposure_time: 500.0
    volume_enabled: true
imaging:
  lm:
    trigger_mode: Hardware
    autosave: false
    color: false
    filter_strength: 0
    camera:
      pin: P14
      max_num_buffer: 5
      image_frame_interval: null
      pixel_size: 5.86e-06
  ib:
    relative_angle: 52
    autosave: false
    filter_strength: 3
  volume:
    time_delay: 0.1
    autosave: true
    count_max: 2
    threshold: 10
  SIM:
    angles: 3
    phases: 3
  crosshairs:
    thickness: 0.1
    length: 10
    color: xkcd:yellow
lamella:
  lamella_width: 1.2e-05
  lamella_height: 1.0e-05
  milling_depth: 5.0e-06
  milling_current: 2.4e-09
  hfw: 0.00015
  upper_height: 5.0e-06
  lower_height: 2.5e-06
